name: routes test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-routes:
    name: "Run unit tests"

    defaults:
      run:
        shell: bash

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: "Checkout repository"

      - name: "Add env file to branch: $GIT_BRANCH"
        run: |
            # Define the directory path
            directory="$PWD"

            echo "root-directory= $directory"

            # Define the file name
            file_name=".env"

            # Create the file in the specified directory
            touch "$file_name"

            #LOCALHOST
            PORT=8000
            HOST="localhost"

            #Viloop logo
            LOGO="../../public/images/viloop-logo"

            #DATABASE
            DATABASE_URL=mongodb+srv://searchingyardpc:RzjTrglVka24hhHY@cluster0.ctnfuur.mongodb.net/TESTING_DB

            # Gmail Credentials
            MAIL_FROM="SearchingYard <noreply@viloop.in>"
            MAIL_PASS="PHtE6r0LR+/ijWUuoxcBs6W9E8T3PIl7/OxvKwAWs9kUCP4FG01So4x6lmfk+B4pUvlEFvGfzdhh4r7P4e+McGi/M21MWWqyqK3sx/VYSPOZsbq6x00bsV8Zf0DZUI/qd9Fu1yLfvdfaNA=="

            #Firebase
            PROJECT_ID="viloop-api"
            PRIVATE_KEY="-----BEGIN PRIVATE KEY-----\\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDETfCEZcfQE1P2\\nliQSe0lx2THcDoOqmYNnBYLU/pRkuCeSymTd/Csu9rDk/N2uqGXSRQHV7z/kAbb1\\ncmiwfP2uOffi+/g0xLBu2wPpFUxLV4vyRzW9kulgoTFq1axseWmnVEgpTGRuCc4E\\nI4c6KrFq07bM6DBgU00nD9yfmYxvIzLGaKTpNyaCIOJxy9J+/QgLKXQR+um1Y2ak\\nQSFDigUJ/EhEjCilsjD5tbgC3a3eZ7/KEzb95JJA9Bo6tbEr/pBsPuyx+mm+y67Z\\nEPXy0+PPsqXNkQBF8PARKTOXfblpo0hQvqQ/mfBiUgfVokp+iMbrUqbmNTKs9OvO\\n6Sfha3qVAgMBAAECggEADzKQgxOFJWMFrlK/3q1sSXPc9BIsl93UKjrnPtmpv+Vw\\n7OCd8ACokDV5ivTXrcCsR1vf0UH5Qovub/CoUbePhThILGrA88bheOecVSR4uGGB\\n/GMOckuIJVq9Ym3B8FDzAMkZ4BahtNIuAKyGeNaazzAuWA1Gx4JTeAl2lWWUFXtz\\nqfMpREoDb1pdVZ2skDeoUTnJa5bwX5Ji/1Glbozeu86L7G+OPinrWS9s8m7JnN+8\\n/3SWFEdvFGqK2DO9TIfZazi4/JNDxkplhOTNzNzrW7I+wCaggUqupTmcFjro9XWd\\n15qEsU61Hw1I9Q9GjFaRoDMW2Mc11UWeA+gzRcWHUQKBgQDhwbqYlKYSoSEd+aFa\\nRSjFMqHvXFFHNyIihv4tN8hmFYZvHfvhf1Duo6FUCEdAhzqdUMNgvbpkXjxyFHno\\nqbou5aYaz6ab5UkCBJ2ldVH9WSrP3kWUyOY8+dHnGP0Bse2rAEQ7LIg1Xe6yX14F\\nt7nebVxOodNy/s9XfMN+LqL9JQKBgQDemia9dTXHe6S/lrqjUhMaHwx2RdwXpqTw\\nHssOxw7kaTanQ2zjBaA9bJTrgp3+QQVoPpO8bJCv8WTVSEY6P25TKuLty9yil/jt\\nhldaJOVgEXZkrew27iQ++M1po/Qp3icmZ3r9BQW5xJQssF4LzmiV7s7y+KHY4kHr\\nyOWDDPhksQKBgET/bsY/eFptQK/mobfzNzi99twvPPAlG5ut4nVzfR4mKgZABcGv\\npc6p2B7UwOIp8nIuQuiIVDVkz9iWBYRki3DV42SCXot7Eks5mez95GcoH3uUlXOZ\\nyzSLremRq5IfDWKcHD5xp9eXs+J0X0okEvy2M+Ycc4HL+xbkHOOt4Ua5AoGAQJwh\\njnAM0f+zS+Cl/219GeHVLicMwNifmwp1Ca8BRY68TEQnwKULY4i2mLzqureIqD8x\\nhklEnazFBZrat2Fd1knmX/sB6TePCvIpPILlCMNIx+QrYa4xWw3AIV9zKQvP9Ten\\n3PSuOsMx9t6iDW81r/8GlkNQRrE1TQichTMojaECgYEAhSspt3nBw/JHcLyJECKU\\nNgwgptO1SN9LD6hXaelEMQOIrEWtIbEUBr2GhUYaVNWkQbD/PPmJpXqYTroGzE9V\\nmlb5j8vPkQTOYFzonDaU/+ECj+1mfbFNt7+io2vexry47WmEEQSeo7utX5QUn/hC\\noBYSxNKqGSgFxVXz1FIDH9c=\\n-----END PRIVATE KEY-----\\n"
            CLIENT_EMAIL="firebase-adminsdk-1cqae@viloop-api.iam.gserviceaccount.com"

            #JWT SECRET KEY
            JWT_SECRET="jwt-secret"

            # Concatenate variables with desired text
            content="PORT= $PORT\nHOST= $HOST\nDATABASE_URL= $DATABASE_URL\nMAIL_FROM= $MAIL_FROM\nMAIL_PASS= $MAIL_PASS\nPROJECT_ID= $PROJECT_ID\nPRIVATE_KEY= $PRIVATE_KEY\nCLIENT_EMAIL= $CLIENT_EMAIL\nJWT_SECRET= $JWT_SECRET\nAWS_BUCKET_NAME= $AWS_BUCKET_NAME\nAWS_REGION= $AWS_REGION\nAWS_CLOUD_FONT_DISTRIBUTION_ID= $AWS_CLOUD_FONT_DISTRIBUTION_ID\nAWS_SECRETACCESSKEY= $AWS_SECRETACCESSKEY\nAWS_ACCESSKEYID= $AWS_ACCESSKEYID\nAWS_CLOUD_FONT= $AWS_CLOUD_FONT\nCASHFREE_CLIENT_ID= $CASHFREE_CLIENT_ID\nCASHFREE_SECRET_ACCESS_KEY= $CASHFREE_SECRET_ACCESS_KEY\nCASHFREE_ENV= $CASHFREE_ENV\nPAYMENT_END_POINT= $PAYMENT_END_POINT"

            # Check if the file was created successfully
            if [ -f "$file_name" ] && [ -n "$content" ]; then
                # echo "File '$file_name' created successfully."
                echo -e "$content" > "$file_name"
                echo "content pused to '$file_name' successfully."
            else
                echo "Failed to create file '$file_name'."
            fi

      - uses: actions/setup-node@v4
        name: "Setup node.js"
        with: 
          node-version: "20"

      - name: "Install dependencies"
        run: npm i
        
      - name: "Run tests"
        run: npm run test
