name: routes test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-routes:
    runs-on: ubuntu-latest
    steps:
      - user: actions/checkout@v2
        name: "Checkout repository"

      - name: "Install dependencies"
        run: npm i

      - name: "Run tests"
        run: npm run test
