name: routes test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-routes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: "Checkout repository"

      - name: "Install dependencies"
        run: npm i
          with: 
            node-version: "20"

      - name: "Run tests"
        run: npm run test
